### ISSUE TITLE
Issue: Channel not working for Demo Account #2

### ISSUE THREAD

**Issue by cubeydice** [cubeydice/dupecord#9]
When attempting to access https://dupecord.onrender.com/channels/2/4, the page no longer displays anything but the background.

The following information is logged to the console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'avatarUrl')
    at iC (index.jsx:4:46)
    at ki (react-dom.production.min.js:167:137)
    at Mc (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at ss (react-dom.production.min.js:273:245)
    at _a (react-dom.production.min.js:127:105)
    at us (react-dom.production.min.js:274:82)
    at Object.notify (Subscription.js:16:7)
```

Need to update so that an undefined avatarURL does not break the page. Error occurs at the MessageItem component.

**Comment by cubeydice** [comment]
Issue fixed with commit [950140c](https://github.com/cubeydice/dupecord/commit/950140cf1e57b591e19aa04b1b9ce29a5da3d8fe)
